### ISSUE TITLE
availabilityAtOrFrom key missing

### ISSUE THREAD

**Issue by dchud** [gwu-libraries/launchpad#1033]
Key lookup is not defensive enough:

```python
Traceback (most recent call last):

  File "/launchpad/m31_001/launchpad/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/launchpad/current/launchpad/lp/ui/views.py", line 616, in availability
    json.dumps(db.get_availability(bibid), indent=2),

  File "/launchpad/current/launchpad/lp/ui/db.py", line 117, in get_availability
    results['offers'] = _get_offers_z3950(bibid, 'Georgetown')

  File "/launchpad/current/launchpad/lp/ui/db.py", line 525, in _get_offers_z3950
    o['availabilityAtOrFrom'] = o['availabilityAtOrFrom'].lstrip('.')

KeyError: 'availabilityAtOrFrom'


<WSGIRequest
path:/availability,
GET:<QueryDict: {u'bibid': [u'b30192651']}>,
```

**Comment by cummingsm** [comment]
Key error resolved. However the item page doesn't show the two GT items from their catalog at http://catalog.library.georgetown.edu/record=b3019265~S4 probably since Summon has the value 30192651 (extra digit =1)
