### ISSUE TITLE
Error with DDA link logic

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/launchpad#1208]
Getting this error occasionally. Can be reproduced by going to:

https://findit.library.gwu.edu/item/17586932 

```
unable to render bibid: 17586932
Traceback (most recent call last):
  File "/launchpad/current/launchpad/lp/ui/views.py", line 72, in item
    holdings = voyager.get_holdings(bib)
  File "/launchpad/current/launchpad/lp/ui/voyager.py", line 661, in get_holdings
    holding['ONLINE'] = get_links(holding, dda_isbn, dda_title)
  File "/launchpad/current/launchpad/lp/ui/voyager.py", line 1828, in get_links
    '/?title=' + title + '&isbn=' + isbn
TypeError: cannot concatenate 'str' and 'NoneType' objects

Request repr(): unavailable
```

**Comment by lwrubel** [comment]
Closed by #1215.
