### ISSUE TITLE
unicode for "bad" GT records in marc.json not working

### ISSUE THREAD

**Issue by dchud** [gwu-libraries/launchpad#780]
High-bibid records that produce character handling errors in "old launchpad" render fine in detail view in "new launchpad" but the marc.json view errors out with similar character handling errors.

Note that we believe these are due to one or more issues with recent batch loads of records from GT's catalog, which resulted in a number of "bad"-seeming records with oddly-encoded characters; ideally they will be cleaned up, but our app should still handle this problem with more resilience.

e.g., old launchpad:

  http://findit.library.gwu.edu/item/13719713
  (clean error message in ui, traceback below)

```python
Traceback (most recent call last):

 File "/launchpad/current/launchpad/lp/ui/views.py", line 50, in item
   bib = voyager.get_bib_data(bibid)

 File "/launchpad/current/launchpad/lp/ui/voyager.py", line 122, in get_bib_data
   rec = get_marc_blob(bibid)

 File "/launchpad/current/launchpad/lp/ui/voyager.py", line 92, in get_marc_blob
   rec = pymarc.record.Record(data=raw_marc)

 File "/launchpad/m16_004/launchpad/ENV/lib/python2.7/site-packages/pymarc/record.py", line 70, in __init__
   utf8_handling=utf8_handling)

 File "/launchpad/m16_004/launchpad/ENV/lib/python2.7/site-packages/pymarc/record.py", line 298, in decode_marc
   data = data.decode('utf-8', utf8_handling)

 File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
   return codecs.utf_8_decode(input, errors, True)

UnicodeDecodeError: 'utf8' codec can't decode byte 0xa9 in position 8: invalid start byte
```

in "new launchpad":

  http://gwdev-edsu.wrlc.org/item/13719713
  (renders fine :)

in new launchpad w/marc.json:

  http://gwdev-edsu.wrlc.org/item/13719713/marc.json
  (errors out, traceback below)

"Unicode error hint

The string that could not be encoded/decoded was: 11], �2011."

```python
Traceback:
File "/opt/launchpad/ENV/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  115.                         response = callback(request, *callback_args, **callback_kwargs)
File "/opt/launchpad/ENV/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapped_view
  91.                     response = view_func(request, *args, **kwargs)
File "/opt/launchpad/lp/ui/views.py" in item_marc
  149.     return HttpResponse(rec.as_json(indent=2), content_type='application/json')
File "/opt/launchpad/ENV/lib/python2.7/site-packages/pymarc/record.py" in as_json
  399.         return json.dumps(self.as_dict(), **kwargs)
File "/usr/lib/python2.7/json/__init__.py" in dumps
  238.         **kw).encode(obj)
File "/usr/lib/python2.7/json/encoder.py" in encode
  203.             chunks = list(chunks)
File "/usr/lib/python2.7/json/encoder.py" in _iterencode
  428.             for chunk in _iterencode_dict(o, _current_indent_level):
File "/usr/lib/python2.7/json/encoder.py" in _iterencode_dict
  402.                 for chunk in chunks:
File "/usr/lib/python2.7/json/encoder.py" in _iterencode_list
  326.                 for chunk in chunks:
File "/usr/lib/python2.7/json/encoder.py" in _iterencode_dict
  402.                 for chunk in chunks:
File "/usr/lib/python2.7/json/encoder.py" in _iterencode_dict
  402.                 for chunk in chunks:
File "/usr/lib/python2.7/json/encoder.py" in _iterencode_list
  326.                 for chunk in chunks:
File "/usr/lib/python2.7/json/encoder.py" in _iterencode_dict
  384.                 yield _encoder(value)

Exception Type: UnicodeDecodeError at /item/13719713/marc.json
Exception Value: 'utf8' codec can't decode byte 0xa9 in position 8: invalid start byte
```

**Comment by cummingsm** [comment]
Need an example, since 13719713 has been modified and no longer throws the error.
